### ISSUE TITLE
Implicit Flow should provide a method by which to require TLS

### ISSUE THREAD

**Issue by itsjamie** [ory/fosite#148] opened 2017-03-07 01:20 UTC
In the code for the implicit flow, it is explicitly mentioned that HTTPS isn't a requirement for the flow because the data can't be leaked in the headers. While this is true, I still feel that TLS should be required because it helps prevent sending the token to a domain the browser doesn't trust.

With things like Key pinning, and HSTS, and other techniques, I feel that having the trust and confidentiality via TLS gives some peace of mind that the browser can do a best effort to prevent leaking your token in the fragment..

The spec outlines this as part of the Threat Model in RFC6819, where the code links to.
https://tools.ietf.org/html/rfc6819#section-4.4.2
```
Threat: Access Token Leak in Transport/Endpoints
   This token might be eavesdropped by an attacker.  The token is sent
   from the server to the client via a URI fragment of the redirect URI.
   If the communication is not secured or the endpoint is not secured,
   the token could be leaked by parsing the returned URI.

   Impact: The attacker would be able to assume the same rights granted
   by the token.

   Countermeasures:
   o  The authorization server should ensure confidentiality (e.g.,
      using TLS) of the response from the authorization server to the
      client (see Section 5.1.1).
```

While technically not required, I feel like this should be enforced by default, and (maybe) be relaxed.

Thanks!

**Comment by arekkas** [comment] 2017-03-08 07:51
The problem is that it's not unlikely to be a localhost app, or a custom uri scheme which do not support (CA signed) TLS when using implicit. However, of course, I like the idea of tightening up security. I'm not sure how to proceed, any ideas?

**Comment by itsjamie** [comment] 2017-03-08 14:45
I imagine it would have to be a setting on the client.

So you would be able to put a client into a "production" mode. If the client was in a production mode, you could provide hooks to the client implementation to extend upon the validation with custom logic?

**Comment by arekkas** [comment] 2017-03-08 14:47
That sounds complicated. We could probably just check if it's an (internet) FQDN and if yes, we check for https. If not, we skip it. What do you think?

**Comment by itsjamie** [comment] 2017-03-08 14:57
You're right it is more complicated than needed and puts more onus on the implementor.

So just to make sure I'm understanding, what your proposing is this would make the following an error.
* setting up a client with a implicit flow that redirects to http://
** with the exception of `http://localhost` to allow loopback flows

**Comment by arekkas** [comment] 2017-03-09 11:48
Yup, that's the idea

**Comment by arekkas** [comment] 2017-03-21 11:36
Was your question answered? If yes, can I close the issue?

**Comment by itsjamie** [comment] 2017-03-22 06:33
Curious if you would accept a PR on the implicit grant handler to do the above for the example? I was looking at it because we currently use osin, and I was considering switching and saw in the README 
```Fosite ensures that redirect URIs use https except localhost but you need to implement TLS for the token and auth endpoints yourself.```

If not, feel free to close. Thanks!

**Comment by arekkas** [comment] 2017-03-22 09:15
I quickly scanned the [implicit flow code base](https://github.com/ory/fosite/blob/master/handler/oauth2/flow_authorize_implicit.go) and it doesn't seem like it's enforcing https (this is the [counter example](https://github.com/ory/fosite/blob/master/handler/oauth2/flow_authorize_code_auth.go#L44-L46)). Can you confirm this in your implementation?

If it already works as specified, I'd gladly accept a PR that improves the wording in the readme. If it doesn't work as specified, I gladly accept a PR that fixes that :)

**Comment by arekkas** [comment] 2017-06-09 09:49
Closing due to inactivity

**Closed by arekkas** 2017-06-09 09:49 UTC
Labels: question
